services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - shared:/shared
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  shared:
  db-data:
